-- This file is for use with Corona(R) SDK
--
-- This file is automatically generated with PhysicsEdtior (http://physicseditor.de). Do not edit
--
-- Usage example:
--			local scaleFactor = 1.0
--			local physicsData = (require "shapedefs").physicsData(scaleFactor)
--			local shape = display.newImage("objectname.png")
--			physics.addBody( shape, physicsData:get("objectname") )
--

-- copy needed functions to local scope
local unpack = unpack
local pairs = pairs
local ipairs = ipairs

local M = {}

function M.physicsData(scale)
	local physics = { data =
	{ 
		
		["pick-axe2"] = {

                    {
                    pe_fixture_id = "", density = 1, friction = 0.3, bounce = 1,  isSensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   62, -90  ,  62, -67  ,  -61, -67  ,  -64, -90  }
                    }
      
		},
--		["pick-axe2"] = {
--                   
--                  
--                    
--                   {
--                    pe_fixture_id = "pick-axe", density = 1, friction = 0.3, bounce = 1, isSensor=true, 
--                   filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
--                    radius = 98.046
--                    }
--                    
--                    
--		},
--		["Cart"] = {
--                    
--                    
--                    
--                    
--                    {
--                    pe_fixture_id = "", density = 1, friction = 0.3, bounce = 1, isSensor=true,
--                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
--                    shape = {   -116, -38  ,  118, -39  ,  106, -19  ,  -107, -18  }
--                    }
--                    
--                    
--                    
--		},
		["Cart"] = {

                    {
                    pe_fixture_id = "Cart", density = 1, friction = 0.3, bounce = 1, isSensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -107, -20  ,  108, -19  ,  108, -3  ,  -109, -3  }
                    }
       
		},
		["blue_gem"] = {

                    {
                    pe_fixture_id = "blue_gem", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   30, -11  ,  12, 21  ,  -11, 21  ,  -32, -12  }
                    }
           
		},
		["red_gem"] = {

                    {
                    pe_fixture_id = "red_gem", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, 20  ,  -25, -18  ,  25, -18  }
                    }
          
		},
		["purple_gem"] = {

                    {
                    pe_fixture_id = "purple_gem", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, 17  ,  -18, -17  ,  19, -18  }
                    }
           
		},
		["tri_gem"] = {

                    {
                    pe_fixture_id = "tri_gem", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   0, 9  ,  -16, -15  ,  14, -15  }
                    }
    
		},
--		["rock"] = {
--                    
--                    
--                    
--                    
--                    {
--                    pe_fixture_id = "rock", density = 1, friction = 0.3, bounce = 1, 
--                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
--                    shape = {   61, -66.5  ,  91, 33.5  ,  -59, 62.5  ,  -76, -68.5  }
--                    }
--                    
--                    
--                    
--		}
		["rock"] = {

                    {
                    pe_fixture_id = "rock", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   40, -40  ,  64, -24  ,  47, 38  ,  -1, 44  ,  -41, 36  ,  -62, -42  }
                    }
       
		},
		["shield"] = {

                    {
                    pe_fixture_id = "shield", density = 1, friction = 0, bounce = 0, isSensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   90, -109.5  ,  89, -142.5  ,  164.666656494141, -86.5  ,  206, -13.5  ,  210, 101.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "shield", density = 1, friction = 0, bounce = 0, isSensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   90, -109.5  ,  -95, -108.5  ,  -77, -150.5  ,  -2, -160.5  ,  89, -142.5  }
                    }
                     ,
                    {
                    pe_fixture_id = "shield", density = 1, friction = 0, bounce = 0, isSensor=true, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -201, 120.5  ,  -210, 17.5  ,  -161, -86.5  ,  -77, -150.5  }
                    }

		},
		["LRock1"] = {
                    {
                    pe_fixture_id = "LRock1", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   61.5, 75  ,  -62.5, 28  ,  -62.5, -51  ,  75.5, -76  }
                    }        
		}, 
		["LRock2"] = {
                    {
                    pe_fixture_id = "LRock2", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   101.5, -12.5  ,  42.5, 70.5  ,  -65.5, 86.5  ,  -98.5, 15.5  ,  -52.5, -89.5  }
                    }   
		}, 
		["LRock3"] = {
                    {
                    pe_fixture_id = "LRock3", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   -54, 45  ,  -54, -38  ,  0, -72  ,  52, -44  ,  49, 40  ,  2, 78  }
                    }         
		},		["bloodGem"] = {
                    {
                    pe_fixture_id = "blood_gem", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, 15  ,  11, 45  ,  -11, 45  ,  -33, 18  ,  1, -46  }
                    }   
		}, 
		["apple"] = {
			{                    					pe_fixture_id = "apple", density = 1, friction = 0.3, bounce = 1, 
                    filter = { categoryBits = 1, maskBits = 65535, groupIndex = 0 },
                    shape = {   33, -29  ,  33, 14  ,  -2, 29  ,  -34, 17  ,  -36, -29  }
                    }      
		}
		
	} }

        -- apply scale factor
        local s = scale or 1.0
        for bi,body in pairs(physics.data) do
                for fi,fixture in ipairs(body) do
                    if(fixture.shape) then
                        for ci,coordinate in ipairs(fixture.shape) do
                            fixture.shape[ci] = s * coordinate
                        end
                    else
                        fixture.radius = s * fixture.radius
                    end
                end
        end
	
	function physics:get(name)
		return unpack(self.data[name])
	end

	function physics:getFixtureId(name, index)
                return self.data[name][index].pe_fixture_id
	end
	
	return physics;
end

return M

